/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeddingsRouteImport } from './routes/weddings'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SculpturesRouteImport } from './routes/sculptures'
import { Route as MemorialsRouteImport } from './routes/memorials'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WeddingsRoute = WeddingsRouteImport.update({
  id: '/weddings',
  path: '/weddings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SculpturesRoute = SculpturesRouteImport.update({
  id: '/sculptures',
  path: '/sculptures',
  getParentRoute: () => rootRouteImport,
} as any)
const MemorialsRoute = MemorialsRouteImport.update({
  id: '/memorials',
  path: '/memorials',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/memorials': typeof MemorialsRoute
  '/sculptures': typeof SculpturesRoute
  '/shop': typeof ShopRoute
  '/weddings': typeof WeddingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/memorials': typeof MemorialsRoute
  '/sculptures': typeof SculpturesRoute
  '/shop': typeof ShopRoute
  '/weddings': typeof WeddingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/memorials': typeof MemorialsRoute
  '/sculptures': typeof SculpturesRoute
  '/shop': typeof ShopRoute
  '/weddings': typeof WeddingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/memorials'
    | '/sculptures'
    | '/shop'
    | '/weddings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/memorials'
    | '/sculptures'
    | '/shop'
    | '/weddings'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/memorials'
    | '/sculptures'
    | '/shop'
    | '/weddings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  MemorialsRoute: typeof MemorialsRoute
  SculpturesRoute: typeof SculpturesRoute
  ShopRoute: typeof ShopRoute
  WeddingsRoute: typeof WeddingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weddings': {
      id: '/weddings'
      path: '/weddings'
      fullPath: '/weddings'
      preLoaderRoute: typeof WeddingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sculptures': {
      id: '/sculptures'
      path: '/sculptures'
      fullPath: '/sculptures'
      preLoaderRoute: typeof SculpturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memorials': {
      id: '/memorials'
      path: '/memorials'
      fullPath: '/memorials'
      preLoaderRoute: typeof MemorialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  MemorialsRoute: MemorialsRoute,
  SculpturesRoute: SculpturesRoute,
  ShopRoute: ShopRoute,
  WeddingsRoute: WeddingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
